/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.web.organizer.ui;

import com.vaadin.ui.Label;

/**
 *
 * @author Gery
 */
public class TermsContent extends BaseContent {

    public TermsContent() {
        Label terms = new Label(
                "<h2>OrganizedLife Terms & Conditions of Use</h2>"
                + "<p>We are required by law to inform you that the terms and conditions are in English and that we will communicate with you in English. To the extent any translated version of this agreement conflicts with the English version, the English version controls.</p>"
                + "<h3>1. About the OrganizedLife Online Service Terms of Service</h3>"
                + "<p>Within these Web Services Terms of Service (Terms) the term OrganizedLife or we will refer to OrganizedLife Ltd, and their affiliates that own and operate Websites and Internet services on their behalf. The term you refers to you as a user of OrganizedLife Website or Services. </p>"
                + "<h3>These Terms & Conditions of use cover:</h3>"
                + "<p>These Terms set forth the terms and conditions through which OrganizedLife will permit you to use these OrganizedLife website and services:</p>"
                + "<p><b>a.</b> the Website 'www.OrganizedLife.com'</p>"
                + "<p><b>b.</b> the OrganizedLife and other software and services provided directly or indirectly by OrganizedLife, including those services made available through application programming interfaces ('APIs') and services offered through third parties integrating OrganizedLife functionality, collectively the 'OrganizedLife Service').</p>"
                + "<h3>2. Accepting These Terms</h3>"
                + "<p>In order for you to use any of the OrganizedLife Services, you must first agree to abide by the Terms. You can accept these Terms by:</p>"
                + "<p><b>a.</b> Checking the box next to 'I have read and agree to the Terms of Service' (or similar language); or</p>"
                + "<p><b>b.</b>Using the OrganizedLife Service, in which case you understand and agree that these Terms will apply to your use of those services (or any parts of them).It is recommended prior to using the OrganizedLife Services, you should print or save a local copy of the Terms for your records.</p>"
                + "<h3>3. Registration</h3>"
                + "<p>In order to use the OrganizedLife Services you may be required to provide information about yourself (such as identification or contact details) as part of the registration process. You agree that any registration information you give to OrganizedLife will be accurate, correct, and current.</p>"
                + "<h3>4. Prohibited Uses</h3>"
                + "<p>You specifically agree not to:</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;use the OrganizedLife Services to undertake or accomplish any unlawful purpose, including but not limited to, posting, storing, transmitting or disseminating information, data or material which is libellous, obscene, unlawful, threatening or defamatory, or which infringes the intellectual property rights of any person or entity, or which in any way constitutes or encourages conduct that would constitute a criminal offence, or otherwise violate any local, state, federal, or non-U.S. law, order, or regulation;</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;post, store, send, transmit, or disseminate on the OrganizedLife Services any information or material which a reasonable person could deem to be unlawful;</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;post on the OrganizedLife Services unsolicited bulk or commercial messages commonly known as 'spam;'</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;send very large numbers of copies of the same or substantially similar messages, empty messages, or messages which contain no substantive content, or send very large messages or files that disrupt a blog, newsgroup, chat, or similar feature of the OrganizedLife Services;</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;initiate, perpetuate, or in any way participate in any pyramid or other illegal scheme through the OrganizedLife Services;</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;participate in the collection of very large numbers of e-mail addresses, screen names, or other identifiers of others (without their prior consent) from the OrganizedLife Services, a practice sometimes known as spidering, crawling or harvesting, or participate in the use of software (including 'spyware') designed to facilitate this activity;</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;collect responses from unsolicited bulk messages posted on the OrganizedLife Services; </p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;impersonate any person or entity, engage in sender address falsification, forge anyone else's digital or manual signature, or perform any other similar fraudulent activity (for example, 'phishing') on the OrganizedLife Services; </p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;restrict, inhibit, or otherwise interfere with the ability of any other person, regardless of intent, purpose or knowledge, to use or enjoy the OrganizedLife Services (except for tools for safety and security functions such as parental controls, for example), including, without limitation, posting or transmitting any information or software which contains a worm, virus, Trojan, keylogger or other harmful feature, or generating levels of traffic sufficient to impede others' ability to use, send, or retrieve information; </p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;register under the name of, nor attempt to use the OrganizedLife Services under the name of, another person; </p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;allow another person to access the OrganizedLife Services using your credentials; </p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;access (or attempt to access) the OrganizedLife Services through any automated means (including use of scripts or web crawlers), except through APIs or other interfaces specifically provided for this purpose, or violate the instructions set out in any robots.txt or similar file present within the OrganizedLife Services; </p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;engage in the systematic retrieval of data or other content from the OrganizedLife Services, except though APIs or other interfaces specifically provided for this purpose, to create or compile, directly or indirectly, a collection, compilation, database or directory, without OrganizedLife's prior written consent;</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;capture, rip, download, or otherwise create a copy of any content that is shown on the OrganizedLife Sites without obtaining any required permission of the content owner; or </p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;take any actions for the purpose of manipulating or distorting, or that may undermine the integrity and accuracy of, any ratings or reviews of any movie or other entertainment program, service or product that may be presented by the OrganizedLife Service.</p>"
                + "<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•&nbsp;&nbsp;attempt to or actually circumvent any method used by OrganizedLife to control access to the Web Services, including, but not limited to, spoofing or otherwise impersonating an IP address for your computer that is not actually assigned to your computer or setting up a proxy or other device that allows others to access the Web Services through it.</p>"
                + "<h3>5. Your Passwords and Unauthorized Use of Your Account</h3>"
                + "<p>You agree and understand that you are responsible for maintaining the confidentiality of the password(s) you use to access the OrganizedLife Services. Accordingly, you agree that you will be solely responsible to OrganizedLife for all activities that occur under your OrganizedLife accounts, and will be responsible for any breach of these Terms caused by these activities. If you become aware of any unauthorized use of your password or of your account, you agree to notify OrganizedLife immediately.</p>"
                + "<h3>6. Privacy and Your Personal Information</h3>"
                + "<p>To understand how the OrganizedLife Services use information you provide, please read the Web Services Privacy Policy. This policy explains how OrganizedLife and its providers handle your personal information when you register and use the OrganizedLife Services.</p>"
                + "<h3>7. Content on the OrganizedLife Services</h3>"
                + "<p>The OrganizedLife Services will allow you to access information, such as collections of data, video, audio, or other multimedia, and photographs and other static images (the 'Content'). This Content may be owned by OrganizedLife, other companies that give OrganizedLife the right to distribute their Content (like movie publishers), or users of the OrganizedLife Services (like you). OrganizedLife grants you a limited license to view the Content and to use the OrganizedLife Services for personal, non-commercial purposes as set forth in these Terms or in a manner that does not require a license. Unless the Content was legally posted by you on the OrganizedLife Services, you may not distribute copies of the Content in any form (including by e-mail or other electronic means), without prior written permission from its owner except as permitted by law. Of course, you are free to encourage others to access the Content and to tell them how to find it.</p>"
                + "<p>In addition, our Content providers want to remind you that you must not remove, alter, interfere with, or circumvent any copyright, trademark, or other proprietary notices marked on the Content or any digital rights management mechanism, device, or other content protection or access control measure associated with the Content. The copying, downloading, stream capturing, reproduction, duplication, archiving, distribution, uploading, publication, modification, translation, broadcast, performance, display, sale, or transmission of the Content is strictly prohibited unless it is expressly permitted by OrganizedLife in writing. You may not incorporate the Content into any hardware or software application. This prohibition applies even if you intend to give away the derivative materials free of charge.</p>"
                + "<h3>8. User Submissions</h3>"
                + "<p>Some of the material appearing on the OrganizedLife Services will be provided by users. OrganizedLife does not claim ownership of any material that users submit or post on the OrganizedLife Services. You agree that you are solely responsible for (and that OrganizedLife has no responsibility to you or to any third party for) any material that you create, transmit, or display while using the OrganizedLife Services, and for the consequences of your actions (including any loss or damage which OrganizedLife may suffer) by doing so. Further, you agree that, with respect to any communication you submit to us for posting on the OrganizedLife Services, you will not: (i) include any content that violates a third party's copyright or other proprietary or privacy rights; (ii) publish falsehoods or misrepresentations portrayed as fact; (iii) include any advertising or solicitations; or (iv) submit any material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise clearly inappropriate.</p>"
                + "<p>Special Note: When using OrganizedLife Project, we will never reproduce, publicly show or distribute your content posted in this part of the OrganizedLife system, this is because we respect the confidentiality that is required when posting business sensitive information and content.</p>"
                + "<p>The OrganizedLife Services may also contain links to community forums, bulletin boards, chat rooms, and blogs about the various OrganizedLife Services. Children under the age of 13 should not post in any of the forums, boards, chat rooms, blogs, other editorial sections of the OrganizedLife Services. Participants in these forums, bulletin boards, chat rooms, and blogs are solely responsible for all content that they post there. OrganizedLife retains the right, but not the obligation, to correct any errors or omissions in any of this content, as it may determine in its sole discretion. OrganizedLife further reserve the right to delete or remove any content from the forums or blogs without prior notice or liability.</p>"
                + "<p>OrganizedLife reserves the right, but does not assume any obligation, to review any user submission prior to its display on the OrganizedLife Services using automated tools or manual processes. OrganizedLife may refuse to display or remove any user submission from the OrganizedLife Services for any reason in our sole discretion. However, we will typically only do so when we become aware that the material in question is harmful, clearly illegal, or likely to be considered highly offensive or objectionable to a large segment of our users.</p>"
                + "<h3>12. License from OrganizedLife</h3>"
                + "<p>OrganizedLife gives you a worldwide, non-assignable and non-exclusive license to use the OrganizedLife Services for your personal, and commercial use on the terms and conditions described in these Terms. This license is for the sole purpose of enabling you to use and enjoy the benefit of the OrganizedLife Services as provided by OrganizedLife, in the manner permitted by the Terms.</p>"
                + "<h3>13. Discontinuing Use of OrganizedLife</h3>"
                + "<p>Discontinuing Use of the OrganizedLife Services and Termination of the Terms; Provisions That Remain in Effect after Termination</p>"
                + "<p>The Terms apply to all users of the OrganizedLife Services. You can discontinue your use of the OrganizedLife Services so that these Terms no longer apply to you. Registered Users</p>"
                + "<p>If you use any of the OrganizedLife Services (or parts of those services) as a registered user, you may terminate your registered user account at any time. Doing so will delete your account and, because you can no longer use the service associated with that account, terminate the Terms with respect to that service. If you breach any provision of these Terms or other applicable policies, or for any other reason, OrganizedLife reserves the right to restrict, suspend, or terminate your registered user account for any or all of the OrganizedLife Services and terminate the Terms. We may take these actions with or without notice to you. Because registered users are known to us, however, we will generally use reasonable efforts to give notice of these actions. Sections 8, 10, 13 through 16, and 22 of these Terms will survive termination, and shall continue to apply indefinitely.</p>"
                + "<h3>14. EXCLUSION OF WARRANTIES</h3>"
                + "<p>YOU AGREE THAT YOUR USE OF THE ORGANIZEDLIFE SERVICES IS AT YOUR SOLE RISK. BECAUSE OF THE NUMBER OF POSSIBLE SOURCES OF INFORMATION AVAILABLE THROUGH THE ORGANIZEDLIFE SERVICES, AND THE INHERENT HAZARDS AND UNCERTAINTIES OF ELECTRONIC DISTRIBUTION, THERE MAY BE INTERRUPTIONS, DELAYS, OMISSIONS, INACCURACIES, OR OTHER PROBLEMS WITH THIS INFORMATION. IF YOU RELY ON THE ORGANIZEDLIFE SERVICES OR ANY MATERIAL AVAILABLE THROUGH THEM, YOU DO SO AT YOUR OWN RISK. YOU UNDERSTAND THAT YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM ANY MATERIAL AND/OR DATA DOWNLOADED FROM OR OTHERWISE PROVIDED THROUGH THE ORGANIZEDLIFE SERVICES.</p>"
                + "<p>THE ORGANIZEDLIFE SERVICES ARE PROVIDED TO YOU 'AS IS,' 'WITH ALL FAULTS,' AND 'AS AVAILABLE.' ORGANIZEDLIFE AND ITS AGENTS AND LICENSORS CANNOT AND DO NOT WARRANT THE ACCURACY, COMPLETENESS, USEFULNESS, TIMELINESS, NONINFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OF THE INFORMATION AVAILABLE THROUGH THE ORGANIZEDLIFE SERVICES, NOR DO THEY GUARANTEE THAT THE ORGANIZEDLIFE SERVICES WILL BE ERROR-FREE, OR CONTINUOUSLY AVAILABLE, OR THAT THE ORGANIZEDLIFE SERVICES WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>"
                + "<h3>15. LIMITATION OF LIABILITY</h3>"
                + "<p>UNDER NO CIRCUMSTANCES SHALL ORGANIZEDLIFE (INCLUDING ANY SUBSIDIARIES, AND AFFILIATES) OR ITS AGENTS OR LICENSORS BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DAMAGES ARISING OUT OF ANY USE OR MISUSE OF THE ORGANIZEDLIFE SERVICES, INCLUDING, WITHOUT LIMITATION, LIABILITY FOR CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT, OR SIMILAR DAMAGES, EVEN IF ADVISED BEFOREHAND OF THE POSSIBILITY OF THESE DAMAGES, REGARDLESS OF THE FORM OR CAUSE OF ACTION INCLUDING, BUT NOT LIMITED TO, CONTRACT, NEGLIGENCE, AND OTHER TORT ACTIONS. BECAUSE SOME US STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN CATEGORIES OF DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN THESE STATES, THE LIABILITY OF ORGANIZEDLIFE AND ITS AGENTS AND LICENSORS IS LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE STATE LAW. YOU AGREE THAT THE LIABILITY OF ORGANIZEDLIFE (INCLUDING ANY SUBSIDIARIES, AND AFFILIATES) AND ITS AGENTS AND LICENSORS, IF ANY, ARISING OUT OF ANY KIND OF LEGAL CLAIM IN ANY WAY CONNECTED TO THE ORGANIZEDLIFE SERVICES SHALL NOT EXCEED THE AMOUNT YOU PAID TO ORGANIZEDLIFE FOR THE USE OF THE ORGANIZEDLIFE SERVICES.</p>"
                + "<h3>16. Indemnification</h3>"
                + "<p>You agree to indemnify, defend, and hold harmless OrganizedLife (including any subsidiaries, and affiliates and all of their respective officers, directors, employees, agents, licensors, suppliers and any third-party information providers) against all claims, losses, expenses, damages and costs (including reasonable attorney fees) resulting from any breach of the Terms or unauthorized use of the OrganizedLife Services. OrganizedLife reserves the right, at its election to assume the exclusive defence and control of any matter subject to indemnification by you and you agree to cooperate with OrganizedLife in connection with our defence.</p>"
                + "<h3>17. Copyright Infringement</h3>"
                + "<p>OrganizedLife is committed to complying with international copyright and related laws, and requires all users of the OrganizedLife Services to comply with these laws. Accordingly, you may not use the OrganizedLife Services to store any material or content, or disseminate any material or content, in any manner that constitutes an infringement of third party intellectual property rights, including rights granted by U.S. copyright law.</p>"
                + "<h3>18. Other Sites</h3>"
                + "<p>The OrganizedLife Services may contain links to other sites. Some of these other sites may be co-branded with OrganizedLife branding and may look like features of the OrganizedLife Services, but these Websites and resources are provided by companies or persons other than OrganizedLife. OrganizedLife does not control the terms of service or the privacy policies of these sites, and their terms and policies will govern your use of those sites and their use of any information you provide to them through those sites. You acknowledge and agree that OrganizedLife is not responsible for the availability of any of these external sites or resources, and does not endorse any advertising, products or other materials on or available from these Websites or resources. You acknowledge and agree that OrganizedLife is not liable for any loss or damage which may be incurred by you as a result of the availability of those external sites or resources, or as a result of any reliance placed by you on the completeness, accuracy or existence of any advertising, products or other materials on, or available from, these Websites or resources.</p>"
                + "<h3>19. Changes to the Terms</h3>"
                + "<p>OrganizedLife reserves the right to change these Terms from time to time consistent with applicable contract laws and principles. When these changes are made, OrganizedLife will make a copy of the updated Terms available at this web page and will also make any updated Terms available to you by e-mail, direct mail, or other reasonable means as selected by OrganizedLife.</p>"
                + "<p>OrganizedLife will make the updated Terms available to you before they take effect. You understand and agree that if you use the OrganizedLife Services after the date on which the Terms take effect; OrganizedLife will treat your use as acceptance of the updated Terms.</p>"
                + "<h3>20. Trademarks</h3>"
                + "<p>OrganizedLife, the OrganizedLife design logo, is a trademarks or service marks of OrganizedLife Ltd. All other trademarks and service marks appearing on the OrganizedLife Services are the properties of their respective owners.</p>"
                + "<h3>21. Special Note</h3>"
                + "<p>OrganizedLife is not intended for use by, and should not be used by, children under the age of 13. You may not use www.OrganizedLife.com if you are under the age of 13, or to solicit information from children under the age of 13.</p>"
                + "<h3>22. General Legal Terms</h3>"
                + "<p>The Terms constitute the whole legal agreement between you and OrganizedLife Ltd and govern your use of the OrganizedLife Services, and completely replace any prior agreements between you and OrganizedLife in relation to the OrganizedLife Services.</p>"
                + "<p>You agree that OrganizedLife may provide you with notices, including those regarding changes to the Terms, by e-mail, regular mail, or postings on the OrganizedLife Services website.</p>"
                + "<p>You agree that if OrganizedLife does not exercise or enforce any legal right or remedy which is contained in the Terms (or which OrganizedLife has the benefit of under any applicable law), this will not be taken to be a formal waiver of OrganizedLife's rights and that those rights or remedies will still be available to OrganizedLife.</p>"
                + "<p>OrganizedLife complies with the local laws or regulations of the United Kingdom. The OrganizedLife Services are intended to be appropriate for use worldwide in any jurisdiction from which you access it. If you choose to access this Site from a jurisdiction other than the United Kingdom you do so at your own risk and OrganizedLife Ltd will not be liable for any breach of local law or regulation as a result of using the OrganizedLife services.</p>"
                + "<p>If any court of law, having the jurisdiction to decide on this matter, rules that any provision of these Terms is invalid, then that provision will be removed from the Terms without affecting the rest of the Terms. The remaining provisions of the Terms will continue to be valid and enforceable.</p>");

        terms.setContentMode(Label.CONTENT_XHTML);
        addComponent(terms);
    }
}